name: merge queue

on:
  pull_request:
     types: [opened, synchronize]
  push:
    branches:
      - develop
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Print Hello World
      run: echo "Hello, World"
      
    - name: Echo previous commit
      run: echo "Previous commit hash:$(git log --pretty=format:'%H' -n 2 | tail -n 1)"
